VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = no
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
RGB_MATRIX_ENABLE = yes
